services:
  rdt-client:
    image: rogerfar/rdtclient:latest
    container_name: debrid
    restart: unless-stopped
    networks:
      - web
      - arr
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Europe/Lisbon}"
    volumes:
      - ${CONFIG_ROOT:-/mnt/pool/config}/debrid:/data/db
      - ${DATA_ROOT:-/mnt/pool}/downloads:/data/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.debrid.entrypoints=https"
      - "traefik.http.routers.debrid.rule=Host(`debrid.${DOMAIN:-snackk-media.com}`)"
      - "traefik.http.routers.debrid.middlewares=secure-headers@file"
      - "traefik.http.services.debrid.loadbalancer.server.port=6500"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:6500/ || exit 1
      start_period: 20s
      timeout: 3s
      interval: 30s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
  arr:
    external: true
