volumes:
  emby:
    external: true
    name: emby

services:
  emby:
    image: emby/embyserver
    container_name: emby
    restart: unless-stopped
    ports:
      - "8096:8096"
    networks:
      - web
    volumes:
      - emby:/config
      - /media/data/Media/Movies:/mnt/movies
      - /media/data/Media/Shows:/mnt/shows
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "992"
      - "44"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.emby.entrypoints=http"
      - "traefik.http.routers.emby.rule=Host(`emby.snackk-media.com`)"
      - "traefik.http.middlewares.emby-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.emby-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.emby.middlewares=emby-https-redirect"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
      - "traefik.http.routers.emby-secure.entrypoints=https"
      - "traefik.http.routers.emby-secure.rule=Host(`emby.snackk-media.com`)"
      - "traefik.http.routers.emby-secure.tls=true"
      - "traefik.http.routers.emby-secure.tls.certresolver=ssl-cert"
      - "traefik.http.routers.emby-secure.service=emby"
    environment:
      - "UID=1000"
      - "GID=1000"
      - "TZ=Europe/Lisbon"

  seerr:
    image: ghcr.io/seerr-team/seerr
    container_name: seerr
    restart: unless-stopped
    ports:
      - 5055:5055
    networks:
      - web
    volumes:
      - /media/data/Media/seerr_config:/app/config
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Lisbon
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.entrypoints=http"
      - "traefik.http.routers.seerr.rule=Host(`seerr.snackk-media.com`)"
      - "traefik.http.middlewares.seerr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.seerr-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.seerr.middlewares=seerr-https-redirect"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.seerr-secure.entrypoints=https"
      - "traefik.http.routers.seerr-secure.rule=Host(`seerr.snackk-media.com`)"
      - "traefik.http.routers.seerr-secure.tls=true"
      - "traefik.http.routers.seerr-secure.tls.certresolver=ssl-cert"
      - "traefik.http.routers.seerr-secure.service=seerr"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    networks:
      - web
    volumes:
      - /media/data/Media/radarr_config:/config
      - /media/data/Media/Movies:/movies
      - /media/data/Media/:/downloads
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`radarr.snackk-media.com`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.snackk-media.com`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=ssl-cert"
      - "traefik.http.routers.radarr-secure.service=radarr"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    networks:
      - web
    volumes:
      - /media/data/Media/sonarr_config:/config
      - /media/data/Media/Shows:/tv
      - /media/data/Media/:/downloads
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.snackk-media.com`)"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.snackk-media.com`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.tls.certresolver=ssl-cert"
      - "traefik.http.routers.sonarr-secure.service=sonarr"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    networks:
      - web
    volumes:
      - /media/data/Media/prowlarr_config:/config
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Lisbon"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=http"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.snackk-media.com`)"
      - "traefik.http.middlewares.prowlarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.prowlarr-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.prowlarr.middlewares=prowlarr-https-redirect"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.http.routers.prowlarr-secure.entrypoints=https"
      - "traefik.http.routers.prowlarr-secure.rule=Host(`prowlarr.snackk-media.com`)"
      - "traefik.http.routers.prowlarr-secure.tls=true"
      - "traefik.http.routers.prowlarr-secure.tls.certresolver=ssl-cert"
      - "traefik.http.routers.prowlarr-secure.service=prowlarr"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - web
    ports:
      - "8191:8191"
    environment:
      - "LOG_LEVEL=info"
      - "TZ=Europe/Lisbon"

networks:
  web:
    external: true
