services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ${CONFIG_ROOT:?Set CONFIG_ROOT in .env}/emby:/config
      - ${DATA_ROOT:?Set DATA_ROOT in .env}/movies:/data/movies
      - ${DATA_ROOT:?Set DATA_ROOT in .env}/shows:/data/shows
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "${RENDER_GID:?Set RENDER_GID in .env}"
      - "${VIDEO_GID:?Set VIDEO_GID in .env}"
    environment:
      - "UID=${PUID:?Set PUID in .env}"
      - "GID=${PGID:?Set PGID in .env}"
      - "TZ=${TZ:?Set TZ in .env}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.emby.entrypoints=https"
      - "traefik.http.routers.emby.rule=Host(`emby.${DOMAIN:?Set DOMAIN in .env}`)"
      - "traefik.http.routers.emby.middlewares=secure-headers@file"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8096/System/Ping || exit 1
      start_period: 30s
      timeout: 3s
      interval: 30s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true

